//! Code generation for the `arbitrary` and `shrink` method bodies.

use proc_macro2::{Span, TokenStream as TokenStream2};
use quote::quote;
use syn::{spanned::Spanned, DataEnum, Error, Fields, Ident, Path};

use crate::attrs::{ContainerAttrs, FieldAttrs, VariantAttrs};

/// Create a macro-internal identifier with `mixed_site` hygiene, so it can never
/// collide with a user-written identifier of the same spelling (e.g. a
/// `const __quickcheck_field0` parameter).
fn mixed(name: &str) -> Ident {
  Ident::new(name, Span::mixed_site())
}

/// How a single field is generated by `arbitrary`. `g` is the (hygienic)
/// `&mut Gen` parameter ident threaded from `lib.rs`.
fn field_arbitrary_expr(attrs: &FieldAttrs, g: &Ident, qc: &Path) -> TokenStream2 {
  if let Some(with) = &attrs.with {
    quote!(#with(#g))
  } else if attrs.default {
    quote!(::core::default::Default::default())
  } else {
    quote!(#qc::Arbitrary::arbitrary(#g))
  }
}

/// Whether a field participates in shrinking.
fn field_is_shrinkable(attrs: &FieldAttrs) -> bool {
  // Held constant when `default`, or `with` without an explicit `shrink`.
  if attrs.default {
    return false;
  }
  if attrs.with.is_some() && attrs.shrink.is_none() {
    return false;
  }
  true
}

/// The per-field shrink iterator expression, given how to refer to the field's
/// current value (`access`, e.g. `&self.x` or `__quickcheck_field0`).
fn field_shrink_iter(attrs: &FieldAttrs, access: &TokenStream2, qc: &Path) -> TokenStream2 {
  if let Some(shrink) = &attrs.shrink {
    quote!(#shrink(#access))
  } else {
    quote!(#qc::Arbitrary::shrink(#access))
  }
}

/// Generate the `arbitrary` + `shrink` bodies for a struct.
///
/// `g` is the (hygienic) `&mut Gen` parameter ident threaded from `lib.rs`,
/// shared by the impl signature and these bodies.
pub(crate) fn struct_bodies(
  name: &Ident,
  fields: &Fields,
  container: &ContainerAttrs,
  g: &Ident,
  qc: &Path,
) -> syn::Result<(TokenStream2, TokenStream2)> {
  let field_attrs = parse_field_attrs(fields)?;

  // --- arbitrary ---
  let arbitrary = if let Some(with) = &container.with {
    quote!(#with(#g))
  } else {
    let ctor = build_ctor(quote!(#name), fields, &field_attrs, g, qc);
    quote!(#ctor)
  };

  // --- shrink ---
  // Container `shrink` wins; else `with`-without-`shrink` => empty; else derive.
  let shrink = if let Some(shrink) = &container.shrink {
    quote!(#shrink(self))
  } else if container.with.is_some() {
    empty_iter()
  } else {
    struct_shrink(fields, &field_attrs, qc)
  };

  Ok((arbitrary, shrink))
}

/// Generate the `arbitrary` + `shrink` bodies for an enum.
///
/// `g` is the (hygienic) `&mut Gen` parameter ident threaded from `lib.rs`,
/// shared by the impl signature and these bodies.
pub(crate) fn enum_bodies(
  name: &Ident,
  data: &DataEnum,
  container: &ContainerAttrs,
  g: &Ident,
  qc: &Path,
) -> syn::Result<(TokenStream2, TokenStream2)> {
  // --- arbitrary ---
  let arbitrary = if let Some(with) = &container.with {
    quote!(#with(#g))
  } else {
    enum_arbitrary(name, data, g, qc)?
  };

  // --- shrink ---
  // Container `shrink` wins; else `with`-without-`shrink` => empty; else derive.
  let shrink = if let Some(shrink) = &container.shrink {
    quote!(#shrink(self))
  } else if container.with.is_some() {
    empty_iter()
  } else {
    enum_shrink(name, data, qc)?
  };

  Ok((arbitrary, shrink))
}

// ---------------------------------------------------------------------------
// Struct helpers
// ---------------------------------------------------------------------------

/// Parse the per-field `#[quickcheck(...)]` attributes for a field list.
fn parse_field_attrs(fields: &Fields) -> syn::Result<Vec<FieldAttrs>> {
  fields.iter().map(|f| FieldAttrs::parse(&f.attrs)).collect()
}

/// Build a constructor expression for `path` (a struct or variant path) over
/// `fields`, generating each field from `g` per its attributes.
fn build_ctor(
  path: TokenStream2,
  fields: &Fields,
  field_attrs: &[FieldAttrs],
  g: &Ident,
  qc: &Path,
) -> TokenStream2 {
  match fields {
    Fields::Named(named) => {
      let inits = named.named.iter().zip(field_attrs).map(|(f, attrs)| {
        let ident = f.ident.as_ref().expect("named field has ident");
        let expr = field_arbitrary_expr(attrs, g, qc);
        quote!(#ident: #expr)
      });
      quote!(#path { #(#inits),* })
    }
    Fields::Unnamed(unnamed) => {
      let inits = unnamed.unnamed.iter().zip(field_attrs).map(|(_, attrs)| {
        let expr = field_arbitrary_expr(attrs, g, qc);
        quote!(#expr)
      });
      quote!(#path ( #(#inits),* ))
    }
    Fields::Unit => quote!(#path),
  }
}

/// Generate the struct `shrink` body. Shrinks one field at a time, holding the
/// rest at their current value by cloning `self`.
fn struct_shrink(fields: &Fields, field_attrs: &[FieldAttrs], qc: &Path) -> TokenStream2 {
  let chain = mixed("__quickcheck_chain");
  let base = mixed("__quickcheck_base");
  let out = mixed("__quickcheck_out");
  let v = mixed("__quickcheck_v");
  let mut clauses = Vec::new();

  for (member, attrs) in members(fields).zip(field_attrs) {
    if !field_is_shrinkable(attrs) {
      continue;
    }
    let access = quote!(&self.#member);
    let iter = field_shrink_iter(attrs, &access, qc);
    clauses.push(quote! {
      {
        let #base = ::core::clone::Clone::clone(self);
        #chain = ::std::boxed::Box::new(#chain.chain(
          (#iter).map(move |#v| {
            let mut #out = ::core::clone::Clone::clone(&#base);
            #out.#member = #v;
            #out
          })
        ));
      }
    });
  }

  if clauses.is_empty() {
    return quote!(::std::boxed::Box::new(::core::iter::empty()));
  }

  quote! {
    let mut #chain: ::std::boxed::Box<dyn ::std::iter::Iterator<Item = Self>> =
      ::std::boxed::Box::new(::core::iter::empty());
    #(#clauses)*
    #chain
  }
}

/// Iterator of `syn::Member`s (named idents or positional indices) for a field
/// list, suitable for `self.#member` access.
fn members(fields: &Fields) -> impl Iterator<Item = syn::Member> + '_ {
  fields.iter().enumerate().map(|(i, f)| match &f.ident {
    Some(ident) => syn::Member::Named(ident.clone()),
    None => syn::Member::Unnamed(syn::Index::from(i)),
  })
}

// ---------------------------------------------------------------------------
// Enum helpers
// ---------------------------------------------------------------------------

/// Generate the enum `arbitrary` body: uniformly choose a non-skipped variant.
fn enum_arbitrary(
  name: &Ident,
  data: &DataEnum,
  g: &Ident,
  qc: &Path,
) -> syn::Result<TokenStream2> {
  let mut indices = Vec::new();
  let mut arms = Vec::new();

  for variant in &data.variants {
    let vattrs = VariantAttrs::parse(&variant.attrs)?;
    if vattrs.skip {
      continue;
    }

    let arm_index = indices.len();
    indices.push(arm_index);

    let vname = &variant.ident;
    let path = quote!(#name::#vname);

    let build = if let Some(with) = &vattrs.with {
      quote!(#with(#g))
    } else {
      let fattrs = parse_field_attrs(&variant.fields)?;
      build_ctor(path, &variant.fields, &fattrs, g, qc)
    };

    let lit = syn::Index::from(arm_index);
    arms.push(quote!(#lit => #build,));
  }

  if indices.is_empty() {
    return Err(Error::new(
      data.variants.span(),
      "all enum variants are `#[quickcheck(skip)]`; `arbitrary` cannot pick a variant",
    ));
  }

  let index_lits = indices.iter().map(|i| syn::Index::from(*i));

  Ok(quote! {
    match *#g.choose(&[#(#index_lits),*]).unwrap() {
      #(#arms)*
      _ => unreachable!(),
    }
  })
}

/// Generate the enum `shrink` body: match the current variant and shrink it.
fn enum_shrink(name: &Ident, data: &DataEnum, qc: &Path) -> syn::Result<TokenStream2> {
  let empty = empty_iter();
  let mut arms = Vec::new();

  for variant in &data.variants {
    let vattrs = VariantAttrs::parse(&variant.attrs)?;
    let vname = &variant.ident;

    // For the non-field-derived cases, use a non-binding pattern so we never
    // emit unused bindings. The field-derived path builds its own pattern that
    // binds exactly the fields it shrinks.
    let arm = if vattrs.skip {
      let pattern = variant_wildcard_pattern(name, vname, &variant.fields);
      quote!(#pattern => { #empty } , )
    } else if let Some(shrink) = &vattrs.shrink {
      let pattern = variant_wildcard_pattern(name, vname, &variant.fields);
      quote!(#pattern => { #shrink(self) } , )
    } else if vattrs.with.is_some() {
      // `with` without `shrink` ⇒ empty.
      let pattern = variant_wildcard_pattern(name, vname, &variant.fields);
      quote!(#pattern => { #empty } , )
    } else {
      let fattrs = parse_field_attrs(&variant.fields)?;
      let (pattern, body) = variant_shrink(name, vname, &variant.fields, &fattrs, qc);
      quote!(#pattern => { #body } , )
    };

    arms.push(arm);
  }

  if arms.is_empty() {
    // Empty enums are uninhabited; nothing to shrink.
    return Ok(empty_iter());
  }

  Ok(quote! {
    match self {
      #(#arms)*
    }
  })
}

/// A non-binding match pattern for a variant (`Variant`, `Variant(..)`,
/// `Variant { .. }`), used when the arm body does not reference fields.
fn variant_wildcard_pattern(name: &Ident, vname: &Ident, fields: &Fields) -> TokenStream2 {
  match fields {
    Fields::Named(_) => quote!(#name::#vname { .. }),
    Fields::Unnamed(_) => quote!(#name::#vname ( .. )),
    Fields::Unit => quote!(#name::#vname),
  }
}

/// Generate the `(pattern, body)` for a variant's field-derived shrink arm.
///
/// Shrinks one field at a time, rebuilding the whole variant explicitly with the
/// shrunk field and clones of the others. Returns a non-binding pattern + empty
/// body when there is nothing to shrink.
fn variant_shrink(
  name: &Ident,
  vname: &Ident,
  fields: &Fields,
  field_attrs: &[FieldAttrs],
  qc: &Path,
) -> (TokenStream2, TokenStream2) {
  let nothing = (variant_wildcard_pattern(name, vname, fields), empty_iter());

  if matches!(fields, Fields::Unit) {
    return nothing;
  }
  if !field_attrs.iter().any(field_is_shrinkable) {
    return nothing;
  }

  // Match-binding idents for each field — always fresh `__quickcheck_field{i}`
  // bindings (never the user's field idents), so a variant field literally named
  // e.g. `__quickcheck_chain` can't be shadowed by a generated local. Named
  // variants bind via `real_name: __quickcheck_field{i}` (see the pattern below).
  // All are referenced by `rebuild_variant`, so none go unused.
  let chain = mixed("__quickcheck_chain");
  let shrunk = mixed("__quickcheck_shrunk");

  let bind_idents: Vec<Ident> = (0..fields.len())
    .map(|i| mixed(&format!("__quickcheck_field{i}")))
    .collect();

  let is_named = matches!(fields, Fields::Named(_));

  // Per-clause owned "base" idents, so each closure captures its own copies.
  let base_idents: Vec<Ident> = (0..bind_idents.len())
    .map(|i| mixed(&format!("__quickcheck_base{i}")))
    .collect();

  let mut clauses = Vec::new();

  for (i, attrs) in field_attrs.iter().enumerate() {
    if !field_is_shrinkable(attrs) {
      continue;
    }

    // Clone every match-bound reference into a fresh owned value for this
    // closure to capture (and then re-clone per produced item).
    let clones = bind_idents
      .iter()
      .zip(&base_idents)
      .map(|(bound, base)| quote!(let #base = ::core::clone::Clone::clone(#bound);));

    let shrink_target = &base_idents[i];
    let iter = field_shrink_iter(attrs, &quote!(&#shrink_target), qc);

    // Rebuild the variant: shrunk field = __quickcheck_shrunk, others = clones.
    let rebuild = rebuild_variant(name, vname, fields, &base_idents, i, is_named, &shrunk);

    clauses.push(quote! {
      {
        #(#clones)*
        #chain = ::std::boxed::Box::new(#chain.chain(
          (#iter).map(move |#shrunk| {
            #rebuild
          })
        ));
      }
    });
  }

  let pattern = match fields {
    Fields::Named(named) => {
      // `real_name: __quickcheck_field{i}` — bind each field to a fresh internal
      // ident so user field names never become bindings that could collide.
      let binds = named.named.iter().zip(&bind_idents).map(|(f, bind)| {
        let ident = f.ident.as_ref().expect("named field has ident");
        quote!(#ident: #bind)
      });
      quote!(#name::#vname { #(#binds),* })
    }
    Fields::Unnamed(_) => {
      let binds = &bind_idents;
      quote!(#name::#vname ( #(#binds),* ))
    }
    Fields::Unit => unreachable!(),
  };

  let body = quote! {
    let mut #chain: ::std::boxed::Box<dyn ::std::iter::Iterator<Item = Self>> =
      ::std::boxed::Box::new(::core::iter::empty());
    #(#clauses)*
    #chain
  };

  (pattern, body)
}

/// Rebuild a variant value where field `shrunk_index` is the `shrunk` binding and
/// the others are clones of their bound idents.
fn rebuild_variant(
  name: &Ident,
  vname: &Ident,
  fields: &Fields,
  bind_idents: &[Ident],
  shrunk_index: usize,
  is_named: bool,
  shrunk: &Ident,
) -> TokenStream2 {
  if is_named {
    let named = match fields {
      Fields::Named(n) => n,
      _ => unreachable!(),
    };
    let inits = named.named.iter().enumerate().map(|(i, f)| {
      let ident = f.ident.as_ref().expect("named field has ident");
      if i == shrunk_index {
        quote!(#ident: #shrunk)
      } else {
        let bound = &bind_idents[i];
        quote!(#ident: ::core::clone::Clone::clone(&#bound))
      }
    });
    quote!(#name::#vname { #(#inits),* })
  } else {
    let inits = (0..bind_idents.len()).map(|i| {
      if i == shrunk_index {
        quote!(#shrunk)
      } else {
        let bound = &bind_idents[i];
        quote!(::core::clone::Clone::clone(&#bound))
      }
    });
    quote!(#name::#vname ( #(#inits),* ))
  }
}

/// `Box::new(empty())`.
fn empty_iter() -> TokenStream2 {
  quote!(::std::boxed::Box::new(::core::iter::empty()))
}
