//! Code generation for the `arbitrary` and `shrink` method bodies.

use proc_macro2::{Span, TokenStream as TokenStream2};
use quote::quote;
use syn::{DataEnum, DeriveInput, Error, Fields, Ident, Path};

use crate::attrs::{ContainerAttrs, FieldAttrs, VariantAttrs};

/// Allocates macro-internal identifiers that cannot collide with the target
/// type's generic parameters.
///
/// A `const` param bypasses macro hygiene for rustc's E0530 ("let bindings cannot
/// shadow const parameters") and for pattern-binding resolution, and a `type` or
/// `const` param shadows a same-named crate alias in a path (the `extern crate
/// alloc as __quickcheck_alloc;` default Box path), so `Span::mixed_site()` alone
/// is insufficient. Whenever the type has a `type` or `const` param spelled like
/// one of our `__quickcheck_*` internals, we append a trailing-underscore suffix
/// to *every* generated name, long enough that no generated name (which never
/// ends in `_`) can equal any such param. In the common case (no
/// `__quickcheck_*`-named param) the suffix is empty.
pub(crate) struct Hygiene {
  suffix: String,
}

impl Hygiene {
  pub(crate) fn new(input: &DeriveInput) -> Self {
    let max_trailing_underscores = input
      .generics
      .type_params()
      .map(|p| p.ident.to_string())
      .chain(input.generics.const_params().map(|p| p.ident.to_string()))
      .filter(|name| name.starts_with("__quickcheck_"))
      .map(|name| name.chars().rev().take_while(|&c| c == '_').count())
      .max();
    let suffix = match max_trailing_underscores {
      Some(k) => "_".repeat(k + 1),
      None => String::new(),
    };
    Self { suffix }
  }

  /// A `mixed_site` identifier for `base`, suffixed so it cannot collide with a
  /// user `const` parameter.
  pub(crate) fn ident(&self, base: &str) -> Ident {
    Ident::new(&format!("{base}{}", self.suffix), Span::mixed_site())
  }
}

/// How a single field is generated by `arbitrary`. `g` is the (hygienic)
/// `&mut Gen` parameter ident threaded from `lib.rs`. Dispatch order:
///   1. `with = "mod"` → `mod::arbitrary(g)`
///   2. `arbitrary = "fn"` → `fn(g)`
///   3. `default` → `Default::default()`
///   4. otherwise → the field type's own `Arbitrary::arbitrary(g)`
fn field_arbitrary_expr(attrs: &FieldAttrs, g: &Ident, qc: &Path) -> TokenStream2 {
  if let Some(with) = &attrs.with {
    quote!(#with::arbitrary(#g))
  } else if let Some(arb) = &attrs.arbitrary {
    quote!(#arb(#g))
  } else if attrs.default {
    quote!(::core::default::Default::default())
  } else {
    quote!(#qc::Arbitrary::arbitrary(#g))
  }
}

/// Whether a field participates in shrinking. Non-shrinkable cases:
///   - `default` (always held constant);
///   - `arbitrary = "fn"` without an explicit `shrink` (no shrink route).
///
/// Note: `with = "mod"` *is* shrinkable — `mod::shrink` provides the route.
fn field_is_shrinkable(attrs: &FieldAttrs) -> bool {
  if attrs.default {
    return false;
  }
  if attrs.arbitrary.is_some() && attrs.shrink.is_none() {
    return false;
  }
  true
}

/// The per-field shrink iterator expression, given how to refer to the field's
/// current value (`access`, e.g. `&self.x` or `__quickcheck_field0`). Dispatch:
///   1. `with = "mod"` → `mod::shrink(access)`
///   2. `shrink = "fn"` → `fn(access)`
///   3. otherwise → the field type's own `Arbitrary::shrink(access)`
fn field_shrink_iter(attrs: &FieldAttrs, access: &TokenStream2, qc: &Path) -> TokenStream2 {
  if let Some(with) = &attrs.with {
    quote!(#with::shrink(#access))
  } else if let Some(shrink) = &attrs.shrink {
    quote!(#shrink(#access))
  } else {
    quote!(#qc::Arbitrary::shrink(#access))
  }
}

/// Generate the `arbitrary` + `shrink` bodies for a struct.
///
/// `g` is the (hygienic) `&mut Gen` parameter ident threaded from `lib.rs`,
/// shared by the impl signature and these bodies.
pub(crate) fn struct_bodies(
  name: &Ident,
  fields: &Fields,
  container: &ContainerAttrs,
  g: &Ident,
  hyg: &Hygiene,
  box_ty: &Path,
  qc: &Path,
) -> syn::Result<(TokenStream2, TokenStream2)> {
  let field_attrs = parse_field_attrs(fields)?;

  // --- arbitrary ---
  // Dispatch: `with = "mod"` → mod::arbitrary; `arbitrary = "fn"` → fn(g); else
  // build the value field-by-field.
  let arbitrary = if let Some(with) = &container.with {
    quote!(#with::arbitrary(#g))
  } else if let Some(arb) = &container.arbitrary {
    quote!(#arb(#g))
  } else {
    let ctor = build_ctor(quote!(#name), fields, &field_attrs, g, qc);
    quote!(#ctor)
  };

  // --- shrink ---
  // Dispatch: `with = "mod"` → mod::shrink (paired with the gen half above);
  // `shrink = "fn"` → fn(self); `arbitrary`-without-`shrink` ⇒ empty (no shrink
  // route); else derive field-by-field shrink.
  let shrink = if let Some(with) = &container.with {
    quote!(#with::shrink(self))
  } else if let Some(shrink) = &container.shrink {
    quote!(#shrink(self))
  } else if container.arbitrary.is_some() {
    empty_iter(box_ty)
  } else {
    struct_shrink(fields, &field_attrs, hyg, box_ty, qc)
  };

  Ok((arbitrary, shrink))
}

/// Generate the `arbitrary` + `shrink` bodies for an enum.
///
/// `g` is the (hygienic) `&mut Gen` parameter ident threaded from `lib.rs`,
/// shared by the impl signature and these bodies.
pub(crate) fn enum_bodies(
  name: &Ident,
  data: &DataEnum,
  container: &ContainerAttrs,
  g: &Ident,
  hyg: &Hygiene,
  box_ty: &Path,
  qc: &Path,
) -> syn::Result<(TokenStream2, TokenStream2)> {
  // --- arbitrary ---
  let arbitrary = if let Some(with) = &container.with {
    quote!(#with::arbitrary(#g))
  } else if let Some(arb) = &container.arbitrary {
    quote!(#arb(#g))
  } else {
    enum_arbitrary(name, data, g, qc)?
  };

  // --- shrink ---
  let shrink = if let Some(with) = &container.with {
    quote!(#with::shrink(self))
  } else if let Some(shrink) = &container.shrink {
    quote!(#shrink(self))
  } else if container.arbitrary.is_some() {
    empty_iter(box_ty)
  } else {
    enum_shrink(name, data, hyg, box_ty, qc)?
  };

  Ok((arbitrary, shrink))
}

// ---------------------------------------------------------------------------
// Struct helpers
// ---------------------------------------------------------------------------

/// Parse the per-field `#[quickcheck(...)]` attributes for a field list.
fn parse_field_attrs(fields: &Fields) -> syn::Result<Vec<FieldAttrs>> {
  fields.iter().map(|f| FieldAttrs::parse(&f.attrs)).collect()
}

/// Build a constructor expression for `path` (a struct or variant path) over
/// `fields`, generating each field from `g` per its attributes.
fn build_ctor(
  path: TokenStream2,
  fields: &Fields,
  field_attrs: &[FieldAttrs],
  g: &Ident,
  qc: &Path,
) -> TokenStream2 {
  match fields {
    Fields::Named(named) => {
      let inits = named.named.iter().zip(field_attrs).map(|(f, attrs)| {
        let ident = f.ident.as_ref().expect("named field has ident");
        let expr = field_arbitrary_expr(attrs, g, qc);
        quote!(#ident: #expr)
      });
      quote!(#path { #(#inits),* })
    }
    Fields::Unnamed(unnamed) => {
      let inits = unnamed.unnamed.iter().zip(field_attrs).map(|(_, attrs)| {
        let expr = field_arbitrary_expr(attrs, g, qc);
        quote!(#expr)
      });
      quote!(#path ( #(#inits),* ))
    }
    Fields::Unit => quote!(#path),
  }
}

/// Generate the struct `shrink` body. Shrinks one field at a time, holding the
/// rest at their current value by cloning `self`.
fn struct_shrink(
  fields: &Fields,
  field_attrs: &[FieldAttrs],
  hyg: &Hygiene,
  box_ty: &Path,
  qc: &Path,
) -> TokenStream2 {
  let chain = hyg.ident("__quickcheck_chain");
  let base = hyg.ident("__quickcheck_base");
  let out = hyg.ident("__quickcheck_out");
  let v = hyg.ident("__quickcheck_v");
  let mut clauses = Vec::new();

  for (member, attrs) in members(fields).zip(field_attrs) {
    if !field_is_shrinkable(attrs) {
      continue;
    }
    let access = quote!(&self.#member);
    let iter = field_shrink_iter(attrs, &access, qc);
    clauses.push(quote! {
      {
        let #base = ::core::clone::Clone::clone(self);
        #chain = #box_ty::new(#chain.chain(
          (#iter).map(move |#v| {
            let mut #out = ::core::clone::Clone::clone(&#base);
            #out.#member = #v;
            #out
          })
        ));
      }
    });
  }

  if clauses.is_empty() {
    return empty_iter(box_ty);
  }

  quote! {
    let mut #chain: #box_ty<dyn ::core::iter::Iterator<Item = Self>> =
      #box_ty::new(::core::iter::empty());
    #(#clauses)*
    #chain
  }
}

/// Iterator of `syn::Member`s (named idents or positional indices) for a field
/// list, suitable for `self.#member` access.
fn members(fields: &Fields) -> impl Iterator<Item = syn::Member> + '_ {
  fields.iter().enumerate().map(|(i, f)| match &f.ident {
    Some(ident) => syn::Member::Named(ident.clone()),
    None => syn::Member::Unnamed(syn::Index::from(i)),
  })
}

// ---------------------------------------------------------------------------
// Enum helpers
// ---------------------------------------------------------------------------

/// Generate the enum `arbitrary` body: uniformly choose a non-skipped variant.
fn enum_arbitrary(
  name: &Ident,
  data: &DataEnum,
  g: &Ident,
  qc: &Path,
) -> syn::Result<TokenStream2> {
  let mut indices = Vec::new();
  let mut arms = Vec::new();
  // Anchor span for the all-skipped diagnostic. We anchor on the FIRST
  // variant's ident — a narrow, deterministic proc-macro2 span (just the
  // variant name), not the multi-line `data.variants.span()` which rustc
  // renders inconsistently across versions.
  let mut all_skipped_span: Option<proc_macro2::Span> = None;

  for variant in &data.variants {
    let vattrs = VariantAttrs::parse(&variant.attrs)?;
    if vattrs.skip {
      if all_skipped_span.is_none() {
        all_skipped_span = Some(variant.ident.span());
      }
      continue;
    }

    let arm_index = indices.len();
    indices.push(arm_index);

    let vname = &variant.ident;
    let path = quote!(#name::#vname);

    // Variant-level dispatch mirrors the container: `with = "mod"` picks
    // mod::arbitrary; `arbitrary = "fn"` picks fn(g); otherwise build the
    // variant field-by-field.
    let build = if let Some(with) = &vattrs.with {
      quote!(#with::arbitrary(#g))
    } else if let Some(arb) = &vattrs.arbitrary {
      quote!(#arb(#g))
    } else {
      let fattrs = parse_field_attrs(&variant.fields)?;
      build_ctor(path, &variant.fields, &fattrs, g, qc)
    };

    let lit = syn::Index::from(arm_index);
    arms.push(quote!(#lit => #build,));
  }

  if indices.is_empty() {
    let span = all_skipped_span.unwrap_or_else(|| name.span());
    return Err(Error::new(
      span,
      "all enum variants are `#[quickcheck(skip)]`; `arbitrary` cannot pick a variant",
    ));
  }

  let index_lits = indices.iter().map(|i| syn::Index::from(*i));

  Ok(quote! {
    match *#g.choose(&[#(#index_lits),*]).unwrap() {
      #(#arms)*
      _ => unreachable!(),
    }
  })
}

/// Generate the enum `shrink` body: match the current variant and shrink it.
fn enum_shrink(
  name: &Ident,
  data: &DataEnum,
  hyg: &Hygiene,
  box_ty: &Path,
  qc: &Path,
) -> syn::Result<TokenStream2> {
  let empty = empty_iter(box_ty);
  let mut arms = Vec::new();

  for variant in &data.variants {
    let vattrs = VariantAttrs::parse(&variant.attrs)?;
    let vname = &variant.ident;

    // For the non-field-derived cases, use a non-binding pattern so we never
    // emit unused bindings. The field-derived path builds its own pattern that
    // binds exactly the fields it shrinks.
    // Shrink dispatch: skip ⇒ empty (variant never generated anyway);
    // `with = "mod"` ⇒ mod::shrink (paired with gen above);
    // explicit `shrink = "fn"` ⇒ fn(self); `arbitrary`-without-`shrink` ⇒ empty;
    // else derive a field-by-field shrink.
    let arm = if vattrs.skip {
      let pattern = variant_wildcard_pattern(name, vname, &variant.fields);
      quote!(#pattern => { #empty } , )
    } else if let Some(with) = &vattrs.with {
      let pattern = variant_wildcard_pattern(name, vname, &variant.fields);
      quote!(#pattern => { #with::shrink(self) } , )
    } else if let Some(shrink) = &vattrs.shrink {
      let pattern = variant_wildcard_pattern(name, vname, &variant.fields);
      quote!(#pattern => { #shrink(self) } , )
    } else if vattrs.arbitrary.is_some() {
      let pattern = variant_wildcard_pattern(name, vname, &variant.fields);
      quote!(#pattern => { #empty } , )
    } else {
      let fattrs = parse_field_attrs(&variant.fields)?;
      let (pattern, body) = variant_shrink(name, vname, &variant.fields, &fattrs, hyg, box_ty, qc);
      quote!(#pattern => { #body } , )
    };

    arms.push(arm);
  }

  if arms.is_empty() {
    // Empty enums are uninhabited; nothing to shrink.
    return Ok(empty_iter(box_ty));
  }

  Ok(quote! {
    match self {
      #(#arms)*
    }
  })
}

/// A non-binding match pattern for a variant (`Variant`, `Variant(..)`,
/// `Variant { .. }`), used when the arm body does not reference fields.
fn variant_wildcard_pattern(name: &Ident, vname: &Ident, fields: &Fields) -> TokenStream2 {
  match fields {
    Fields::Named(_) => quote!(#name::#vname { .. }),
    Fields::Unnamed(_) => quote!(#name::#vname ( .. )),
    Fields::Unit => quote!(#name::#vname),
  }
}

/// Generate the `(pattern, body)` for a variant's field-derived shrink arm.
///
/// Mirrors struct shrink: clone the whole `self` as a base, then per produced
/// item clone the base and mutate just the shrunk field in place (via a
/// `match &mut out` on the variant). This depends only on `Self: Clone` — never
/// on individual fields being `Clone` — so held / `default` / `with` fields that
/// are not `Clone` are fine. Returns a non-binding pattern + empty body when
/// there is nothing to shrink.
fn variant_shrink(
  name: &Ident,
  vname: &Ident,
  fields: &Fields,
  field_attrs: &[FieldAttrs],
  hyg: &Hygiene,
  box_ty: &Path,
  qc: &Path,
) -> (TokenStream2, TokenStream2) {
  // Indices of fields that actually shrink.
  let shrinkable: Vec<usize> = field_attrs
    .iter()
    .enumerate()
    .filter(|(_, a)| field_is_shrinkable(a))
    .map(|(i, _)| i)
    .collect();

  if matches!(fields, Fields::Unit) || shrinkable.is_empty() {
    return (
      variant_wildcard_pattern(name, vname, fields),
      empty_iter(box_ty),
    );
  }

  let chain = hyg.ident("__quickcheck_chain");
  let base = hyg.ident("__quickcheck_base");
  let out = hyg.ident("__quickcheck_out");
  let v = hyg.ident("__quickcheck_v");
  let slot = hyg.ident("__quickcheck_slot");

  // One binding ident per shrinkable field (bound as `&Field` in the outer
  // pattern via default match modes), used to feed that field's shrink iterator.
  let bindings: Vec<(usize, Ident)> = shrinkable
    .iter()
    .map(|&i| (i, hyg.ident(&format!("__quickcheck_field{i}"))))
    .collect();

  let outer_pattern = variant_bind_pattern(name, vname, fields, &bindings);
  let field_count = fields.len();

  let mut clauses = Vec::new();
  for (i, binding) in &bindings {
    let iter = field_shrink_iter(&field_attrs[*i], &quote!(#binding), qc);
    let slot_pattern = variant_slot_pattern(name, vname, fields, *i, field_count, &slot);
    clauses.push(quote! {
      {
        let #base = ::core::clone::Clone::clone(self);
        #chain = #box_ty::new(#chain.chain(
          (#iter).map(move |#v| {
            let mut #out = ::core::clone::Clone::clone(&#base);
            // `out` is always this variant, but a `match` (not `if let`) keeps
            // this warning-free for single-variant enums, where an `if let`
            // would be irrefutable. The wildcard is unreachable only for
            // single-variant enums, hence the `allow`.
            match &mut #out {
              #slot_pattern => *#slot = #v,
              #[allow(unreachable_patterns)]
              _ => {}
            }
            #out
          })
        ));
      }
    });
  }

  let body = quote! {
    let mut #chain: #box_ty<dyn ::core::iter::Iterator<Item = Self>> =
      #box_ty::new(::core::iter::empty());
    #(#clauses)*
    #chain
  };

  (outer_pattern, body)
}

/// Outer match pattern binding exactly the shrinkable fields (by their internal
/// ident, as `&Field`), ignoring the rest.
fn variant_bind_pattern(
  name: &Ident,
  vname: &Ident,
  fields: &Fields,
  bindings: &[(usize, Ident)],
) -> TokenStream2 {
  match fields {
    Fields::Named(named) => {
      let binds = named.named.iter().enumerate().filter_map(|(i, f)| {
        bindings.iter().find(|(bi, _)| *bi == i).map(|(_, ident)| {
          let fname = f.ident.as_ref().expect("named field has ident");
          quote!(#fname: #ident)
        })
      });
      quote!(#name::#vname { #(#binds,)* .. })
    }
    Fields::Unnamed(unnamed) => {
      let elems =
        (0..unnamed.unnamed.len()).map(|i| match bindings.iter().find(|(bi, _)| *bi == i) {
          Some((_, ident)) => quote!(#ident),
          None => quote!(_),
        });
      quote!(#name::#vname ( #(#elems),* ))
    }
    Fields::Unit => unreachable!(),
  }
}

/// `&mut` match pattern binding only field `index` as `slot`, ignoring the rest.
fn variant_slot_pattern(
  name: &Ident,
  vname: &Ident,
  fields: &Fields,
  index: usize,
  field_count: usize,
  slot: &Ident,
) -> TokenStream2 {
  match fields {
    Fields::Named(named) => {
      let fname = named.named[index]
        .ident
        .as_ref()
        .expect("named field has ident");
      quote!(#name::#vname { #fname: #slot, .. })
    }
    Fields::Unnamed(_) => {
      let elems = (0..field_count).map(|i| if i == index { quote!(#slot) } else { quote!(_) });
      quote!(#name::#vname ( #(#elems),* ))
    }
    Fields::Unit => unreachable!(),
  }
}

/// `<box_ty>::new(empty())`.
fn empty_iter(box_ty: &Path) -> TokenStream2 {
  quote!(#box_ty::new(::core::iter::empty()))
}
